{
  "Title": "Gun Dealer",
  "JobImage": "textures/generated/svgsource/23b39010178e4b58.vtex",
  "JobCommandName": "gundealer",
  "Description": "You sell weapons to people, maybe setup a shop/stand with Your rules!",
  "Salary": 30,
  "Color": "1,0.95,0,1",
  "JobClothes": [
    {
      "Clothing": "models/citizen_clothes/shoes/boots/army_boots.clothing"
    },
    {
      "Clothing": "models/citizen_clothes/vest/chefs_apron/chefs_apron.clothing"
    },
    {
      "Clothing": "models/citizen_clothes/hat/bucket_hat/bucket_hat_black.clothing"
    }
  ],
  "JobCategory": "gameplay/jobs/categorys/civillain.category",
  "IsDisableThisJobClothing": false,
  "MaxPlayersAllowedOnJob": 5,
  "IsInfiniteJobSlots": false,
  "SortingLevel": 0,
  "JobHealth": 100,
  "JobHealthMax": 100,
  "JobArmor": 0,
  "JobArmorMax": 100,
  "IsPD": false,
  "IsMayor": false,
  "IsUsingDefaultJobEquipment": true,
  "StartingEquipment": [],
  "IsVoteNeeded": false,
  "PlayTimeNeededToPlay": 0,
  "IsJobWhitelistEnabled": false,
  "IsForUserGroups": false,
  "UserGroupThatCanUseJob": [],
  "HasTempPlayTime": false,
  "TempPlayTimeTotalAmount": 0,
  "IsForSteamUsers": false,
  "SteamIDsThatCanUseJob": [],
  "Prefab": null,
  "__references": [],
  "__version": 0
}