{
  "Title": "Mob Boss",
  "JobImage": "textures/generated/svgsource/30a6616ba1c8c5a0.vtex",
  "JobCommandName": "mobboss",
  "Description": "You are the leader of the Mob.. You can command any thiefs around to organize crime throughout the city.",
  "Salary": 30,
  "Color": "0.43256,0.43256,0.43256,1",
  "JobClothes": [
    {
      "Clothing": "models/citizen_clothes/hat/baseball_cap/baseball_cap_brown.clothing"
    }
  ],
  "JobCategory": "gameplay/jobs/categorys/criminals.category",
  "IsDisableThisJobClothing": true,
  "MaxPlayersAllowedOnJob": 1,
  "IsInfiniteJobSlots": false,
  "SortingLevel": 0,
  "JobHealth": 100,
  "JobHealthMax": 100,
  "JobArmor": 0,
  "JobArmorMax": 0,
  "IsPD": false,
  "IsMayor": false,
  "IsUsingDefaultJobEquipment": false,
  "StartingEquipment": [
    "gameplay/equipment/usp.swep",
    "gameplay/equipment/unarrestbaton.swep"
  ],
  "IsVoteNeeded": false,
  "PlayTimeNeededToPlay": 0,
  "IsJobWhitelistEnabled": false,
  "IsForUserGroups": false,
  "UserGroupThatCanUseJob": [],
  "HasTempPlayTime": false,
  "TempPlayTimeTotalAmount": 0,
  "IsForSteamUsers": false,
  "SteamIDsThatCanUseJob": [],
  "Prefab": null,
  "__references": [],
  "__version": 0
}