{
  "Title": "Thief",
  "JobImage": "textures/generated/svgsource/254ef6613b701a66.vtex",
  "JobCommandName": "thief",
  "Description": "You are a regular thief that can go around and mug, raid, & steal!",
  "Salary": 30,
  "Color": "0.73023,0.73023,0.73023,1",
  "JobClothes": [
    {
      "Clothing": "models/citizen_clothes/hat/bandana_mask/bandana_mask.clothing"
    },
    {
      "Clothing": "models/citizen_clothes/hat/fedora/fedora.clothing"
    },
    {
      "Clothing": "models/citizen_clothes/trousers/cargopants/cargo_pants_army.clothing"
    }
  ],
  "JobCategory": "gameplay/jobs/categorys/criminals.category",
  "IsDisableThisJobClothing": false,
  "MaxPlayersAllowedOnJob": 8,
  "IsInfiniteJobSlots": false,
  "SortingLevel": 0,
  "JobHealth": 100,
  "JobHealthMax": 100,
  "JobArmor": 0,
  "JobArmorMax": 0,
  "IsPD": false,
  "IsMayor": false,
  "IsUsingDefaultJobEquipment": false,
  "StartingEquipment": [],
  "IsVoteNeeded": false,
  "PlayTimeNeededToPlay": 0,
  "IsJobWhitelistEnabled": false,
  "IsForUserGroups": false,
  "UserGroupThatCanUseJob": [],
  "HasTempPlayTime": false,
  "TempPlayTimeTotalAmount": 0,
  "IsForSteamUsers": false,
  "SteamIDsThatCanUseJob": [],
  "Prefab": null,
  "__references": [],
  "__version": 0
}