{
  "Graph": {
    "__version": 9,
    "__guid": "d8b4931d-dc17-430d-8580-1191aac2dc11",
    "__changeId": 30,
    "UserData": {
      "Title": "Microwavelogic",
      "ReferencedComponentTypes": []
    },
    "Parameters": {
      "DefaultSignals": true
    },
    "Variables": [],
    "Nodes": [
      {
        "Id": 0,
        "Type": "input",
        "UserData": {
          "Position": "24,12"
        }
      },
      {
        "Id": 1,
        "Type": "log.info",
        "UserData": {
          "Position": "324,-0"
        }
      }
    ],
    "Links": [
      {
        "SrcId": 0,
        "SrcName": "_signal",
        "DstId": 1,
        "DstName": "_signal"
      },
      {
        "Id": 27,
        "Value": "DID WE CALL?....",
        "DstId": 1,
        "DstName": "format"
      }
    ]
  },
  "__references": [],
  "__version": 0
}